"""Financial document extraction and analysis contracts."""

from .analysis_verifier import (
    AnalysisVerificationError,
    assert_verified_analysis,
    verify_analysis,
)
from .financial_analyzer import (
    METRIC_REGISTRY,
    FinancialMetricSelectionError,
    build_financial_metrics,
    classify_duration,
)
from .pipeline import (
    DEFAULT_FINANCIAL_QUERIES,
    FINANCIAL_ANALYST_SYSTEM_PROMPT,
    GroundedAnalysisError,
    LLMClient,
    PipelineAnalysisError,
    PipelineError,
    PipelineInputError,
    PipelineVerificationError,
    analyze_financials,
    build_analysis_prompt,
    qualitative_analysis_json_schema,
    run_analysis_pipeline,
)
from .openrouter_client import (
    LLMConfigurationError,
    LLMProviderError,
    LLMResponseError,
    LLMTransportError,
    LLMUsage,
    OpenRouterLLMClient,
)
from .schemas import (
    AnalysisPipelineResult,
    ComparisonType,
    DocumentChunk,
    Evidence,
    FinancialAnalysisResult,
    FinancialMetric,
    LoadedDocument,
    LoadedDocumentMetadata,
    ManagementOutlook,
    NormalizedXBRLFact,
    RetrievalResult,
    VerificationIssue,
    VerificationReport,
)

__all__ = [
    "AnalysisPipelineResult",
    "AnalysisVerificationError",
    "ComparisonType",
    "DocumentChunk",
    "DEFAULT_FINANCIAL_QUERIES",
    "Evidence",
    "FINANCIAL_ANALYST_SYSTEM_PROMPT",
    "FinancialAnalysisResult",
    "FinancialMetric",
    "FinancialMetricSelectionError",
    "GroundedAnalysisError",
    "LLMClient",
    "LLMConfigurationError",
    "LLMProviderError",
    "LLMResponseError",
    "LLMTransportError",
    "LLMUsage",
    "LoadedDocument",
    "LoadedDocumentMetadata",
    "ManagementOutlook",
    "METRIC_REGISTRY",
    "NormalizedXBRLFact",
    "OpenRouterLLMClient",
    "PipelineAnalysisError",
    "PipelineError",
    "PipelineInputError",
    "PipelineVerificationError",
    "RetrievalResult",
    "VerificationIssue",
    "VerificationReport",
    "analyze_financials",
    "assert_verified_analysis",
    "build_analysis_prompt",
    "build_financial_metrics",
    "classify_duration",
    "qualitative_analysis_json_schema",
    "run_analysis_pipeline",
    "verify_analysis",
]
